package com.manikssys.in.security.beans;
// Generated Jun 23, 2010 5:14:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ScrButtonMaster generated by hbm2java
 */
public class ScrButtonMaster  implements java.io.Serializable {


     private String buttonId;
     private String buttonName;
     private String status;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private int versionId;
     private Set scrMenuButtonProfileDetailses = new HashSet(0);
     private Set scrMenuButtonDetailses = new HashSet(0);

    public ScrButtonMaster() {
    }

	
    public ScrButtonMaster(String buttonId, String buttonName, int versionId) {
        this.buttonId = buttonId;
        this.buttonName = buttonName;
        this.versionId = versionId;
    }
    public ScrButtonMaster(String buttonId, String buttonName, String userStatus, String createdBy, Date createdDate, String updatedBy, Date updatedDate, int versionId, Set scrMenuButtonProfileDetailses, Set scrMenuButtonDetailses) {
       this.buttonId = buttonId;
       this.buttonName = buttonName;
       this.status = userStatus;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.versionId = versionId;
       this.scrMenuButtonProfileDetailses = scrMenuButtonProfileDetailses;
       this.scrMenuButtonDetailses = scrMenuButtonDetailses;
    }
   
    public String getButtonId() {
        return this.buttonId;
    }
    
    public void setButtonId(String buttonId) {
        this.buttonId = buttonId;
    }
    public String getButtonName() {
        return this.buttonName;
    }
    
    public void setButtonName(String buttonName) {
        this.buttonName = buttonName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String userStatus) {
        this.status = userStatus;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public int getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(int versionId) {
        this.versionId = versionId;
    }
    public Set getScrMenuButtonProfileDetailses() {
        return this.scrMenuButtonProfileDetailses;
    }
    
    public void setScrMenuButtonProfileDetailses(Set scrMenuButtonProfileDetailses) {
        this.scrMenuButtonProfileDetailses = scrMenuButtonProfileDetailses;
    }
    public Set getScrMenuButtonDetailses() {
        return this.scrMenuButtonDetailses;
    }
    
    public void setScrMenuButtonDetailses(Set scrMenuButtonDetailses) {
        this.scrMenuButtonDetailses = scrMenuButtonDetailses;
    }




}


