package com.manikssys.in.security.beans;
// Generated Jun 23, 2010 5:14:05 PM by Hibernate Tools 3.2.1.GA



/**
 * ScrMenuButtonDetails generated by hbm2java
 */
public class ScrMenuButtonDetails  implements java.io.Serializable {


     private String menuButtonDtlsId;
     private ScrMenuMaster scrMenuMaster;
     private ScrButtonMaster scrButtonMaster;
     private String status;

    public ScrMenuButtonDetails() {
    }

	
    public ScrMenuButtonDetails(String menuButtonDtlsId) {
        this.menuButtonDtlsId = menuButtonDtlsId;
    }
    public ScrMenuButtonDetails(String menuButtonDtlsId, ScrMenuMaster scrMenuMaster, ScrButtonMaster scrButtonMaster, String menuButtonStatus) {
       this.menuButtonDtlsId = menuButtonDtlsId;
       this.scrMenuMaster = scrMenuMaster;
       this.scrButtonMaster = scrButtonMaster;
       this.status = menuButtonStatus;
    }
   
    public String getMenuButtonDtlsId() {
        return this.menuButtonDtlsId;
    }
    
    public void setMenuButtonDtlsId(String menuButtonDtlsId) {
        this.menuButtonDtlsId = menuButtonDtlsId;
    }
    public ScrMenuMaster getScrMenuMaster() {
        return this.scrMenuMaster;
    }
    
    public void setScrMenuMaster(ScrMenuMaster scrMenuMaster) {
        this.scrMenuMaster = scrMenuMaster;
    }
    public ScrButtonMaster getScrButtonMaster() {
        return this.scrButtonMaster;
    }
    
    public void setScrButtonMaster(ScrButtonMaster scrButtonMaster) {
        this.scrButtonMaster = scrButtonMaster;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String menuButtonStatus) {
        this.status = menuButtonStatus;
    }




}


