package com.manikssys.in.security.beans;
// Generated Jun 23, 2010 5:14:05 PM by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/**
 * ScrMenuMaster generated by hbm2java
 */
public class ScrMenuMaster  implements java.io.Serializable {


     private String menuId;
     private String menuCode;
     private String menuName;
     private String parentMenuId;
     private Byte menuSequence;
     private String menuAction;
     private String status;
     private Set scrProfileMenuDetailses = new HashSet(0);
     private Set scrMenuButtonProfileDetailses = new HashSet(0);
     private Set scrMenuButtonDetailses = new HashSet(0);
     private ArrayList childList; // Holding Childs

    public ScrMenuMaster() {
    }

	
    public ScrMenuMaster(String menuId, String menuCode, String menuName) {
        this.menuId = menuId;
        this.menuCode = menuCode;
        this.menuName = menuName;
    }
    public ScrMenuMaster(String menuId, String menuCode, String menuName, String parentMenuId, Byte menuSequence, String menuAction, String menuStatus, Set scrProfileMenuDetailses, Set scrMenuButtonProfileDetailses, Set scrMenuButtonDetailses) {
       this.menuId = menuId;
       this.menuCode = menuCode;
       this.menuName = menuName;
       this.parentMenuId = parentMenuId;
       this.menuSequence = menuSequence;
       this.menuAction = menuAction;
       this.status = menuStatus;
       this.scrProfileMenuDetailses = scrProfileMenuDetailses;
       this.scrMenuButtonProfileDetailses = scrMenuButtonProfileDetailses;
       this.scrMenuButtonDetailses = scrMenuButtonDetailses;
    }
   
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
    public String getMenuCode() {
        return this.menuCode;
    }
    
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getParentMenuId() {
        return this.parentMenuId;
    }
    
    public void setParentMenuId(String parentMenuId) {
        this.parentMenuId = parentMenuId;
    }
    public Byte getMenuSequence() {
        return this.menuSequence;
    }
    
    public void setMenuSequence(Byte menuSequence) {
        this.menuSequence = menuSequence;
    }
    public String getMenuAction() {
        return this.menuAction;
    }
    
    public void setMenuAction(String menuAction) {
        this.menuAction = menuAction;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String menuStatus) {
        this.status = menuStatus;
    }
    public Set getScrProfileMenuDetailses() {
        return this.scrProfileMenuDetailses;
    }
    
    public void setScrProfileMenuDetailses(Set scrProfileMenuDetailses) {
        this.scrProfileMenuDetailses = scrProfileMenuDetailses;
    }
    public Set getScrMenuButtonProfileDetailses() {
        return this.scrMenuButtonProfileDetailses;
    }
    
    public void setScrMenuButtonProfileDetailses(Set scrMenuButtonProfileDetailses) {
        this.scrMenuButtonProfileDetailses = scrMenuButtonProfileDetailses;
    }
    public Set getScrMenuButtonDetailses() {
        return this.scrMenuButtonDetailses;
    }
    
    public void setScrMenuButtonDetailses(Set scrMenuButtonDetailses) {
        this.scrMenuButtonDetailses = scrMenuButtonDetailses;
    }

    public ArrayList getChildList() {
        return childList;
    }

    public void setChildList(ArrayList childList) {
        this.childList = childList;
    }


}


