package com.manikssys.in.security.beans;
// Generated Jun 23, 2010 5:14:05 PM by Hibernate Tools 3.2.1.GA



/**
 * ScrMenuButtonProfileDetails generated by hbm2java
 */
public class ScrMenuButtonProfileDetails  implements java.io.Serializable {


     private String mnuButProfDtlsId;
     private ScrMenuMaster scrMenuMaster;
     private ScrButtonMaster scrButtonMaster;
     private ScrUserProfileMaster scrUserProfileMaster;
     private String status;

    public ScrMenuButtonProfileDetails() {
    }

	
    public ScrMenuButtonProfileDetails(String mnuButProfDtlsId) {
        this.mnuButProfDtlsId = mnuButProfDtlsId;
    }
    public ScrMenuButtonProfileDetails(String mnuButProfDtlsId, ScrMenuMaster scrMenuMaster, ScrButtonMaster scrButtonMaster, ScrUserProfileMaster scrUserProfileMaster, String menuButProfStatus) {
       this.mnuButProfDtlsId = mnuButProfDtlsId;
       this.scrMenuMaster = scrMenuMaster;
       this.scrButtonMaster = scrButtonMaster;
       this.scrUserProfileMaster = scrUserProfileMaster;
       this.status = menuButProfStatus;
    }

    public ScrMenuButtonProfileDetails(ScrMenuMaster scrMenuMaster, ScrButtonMaster scrButtonMaster, ScrUserProfileMaster scrUserProfileMaster, String status) {
        this.scrMenuMaster = scrMenuMaster;
        this.scrButtonMaster = scrButtonMaster;
        this.scrUserProfileMaster = scrUserProfileMaster;
        this.status = status;
    }

    public String getMnuButProfDtlsId() {
        return this.mnuButProfDtlsId;
    }
    
    public void setMnuButProfDtlsId(String mnuButProfDtlsId) {
        this.mnuButProfDtlsId = mnuButProfDtlsId;
    }
    public ScrMenuMaster getScrMenuMaster() {
        return this.scrMenuMaster;
    }
    
    public void setScrMenuMaster(ScrMenuMaster scrMenuMaster) {
        this.scrMenuMaster = scrMenuMaster;
    }
    public ScrButtonMaster getScrButtonMaster() {
        return this.scrButtonMaster;
    }
    
    public void setScrButtonMaster(ScrButtonMaster scrButtonMaster) {
        this.scrButtonMaster = scrButtonMaster;
    }
    public ScrUserProfileMaster getScrUserProfileMaster() {
        return this.scrUserProfileMaster;
    }
    
    public void setScrUserProfileMaster(ScrUserProfileMaster scrUserProfileMaster) {
        this.scrUserProfileMaster = scrUserProfileMaster;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String menuButProfStatus) {
        this.status = menuButProfStatus;
    }




}


