/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.manikssys.in.security.beans;

import java.util.Date;

/**
 * ScrSmsHdr generated by hbm2java
 */
public class ScrSmsScheduleMaster  implements java.io.Serializable {


     private Integer id;
     private Date s1UserTime;
     private Date s1BranchTime;
     private Date s1HoTime;
     private Date s2UserTime;
     private Date s2BranchTime;
     private Date s2HoTime;
     private String textMsg;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getS1BranchTime() {
        return s1BranchTime;
    }

    public void setS1BranchTime(Date s1BranchTime) {
        this.s1BranchTime = s1BranchTime;
    }

    public Date getS1HoTime() {
        return s1HoTime;
    }

    public void setS1HoTime(Date s1HoTime) {
        this.s1HoTime = s1HoTime;
    }

    public Date getS1UserTime() {
        return s1UserTime;
    }

    public void setS1UserTime(Date s1UserTime) {
        this.s1UserTime = s1UserTime;
    }

    public Date getS2BranchTime() {
        return s2BranchTime;
    }

    public void setS2BranchTime(Date s2BranchTime) {
        this.s2BranchTime = s2BranchTime;
    }

    public Date getS2HoTime() {
        return s2HoTime;
    }

    public void setS2HoTime(Date s2HoTime) {
        this.s2HoTime = s2HoTime;
    }

    public Date getS2UserTime() {
        return s2UserTime;
    }

    public void setS2UserTime(Date s2UserTime) {
        this.s2UserTime = s2UserTime;
    }

    public String getTextMsg() {
        return textMsg;
    }

    public void setTextMsg(String textMsg) {
        this.textMsg = textMsg;
    }

    @Override
    public String toString() {
        return "ID : "+id+" TEXTMSG : "+textMsg+" s1USer Time : "+s1UserTime+" s1BranchTime "+s1BranchTime+" s1Ho Time "+s1HoTime+" s2USer Time : "+s2UserTime+" s2BranchTime "+s2BranchTime+" s2Ho Time "+s2HoTime;
    }


}



