package com.manikssys.in.security.beans;
// Generated Jun 23, 2010 5:14:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ScrUserProfileMaster generated by hbm2java
 */
public class ScrUserProfileMaster  implements java.io.Serializable {


     private String profileId;
     private String profileCode;
     private String profileName;
     private String status;
     private ScrUserMaster createdBy;
     private Date createdDate;
     private ScrUserMaster updatedBy;
     private Date updatedDate;
     private int versionId;
     private Set scrProfileMenuDetailses = new HashSet(0);
     private Set scrUserMasters = new HashSet(0);
     private Set scrMenuButtonProfileDetailses = new HashSet(0);

    public ScrUserProfileMaster() {
    }

	
    public ScrUserProfileMaster(String profileId, int versionId) {
        this.profileId = profileId;
        this.versionId = versionId;
    }
    public ScrUserProfileMaster(String profileId, String profileCode, String profileName, String profileStatus, String createdBy, Date createdDate, String updatedBy, Date updatedDate, int versionId, Set scrProfileMenuDetailses, Set scrUserMasters, Set scrMenuButtonProfileDetailses) {
       this.profileId = profileId;
       this.profileCode = profileCode;
       this.profileName = profileName;
       this.status = profileStatus;
       this.createdDate = createdDate;
       this.updatedDate = updatedDate;
       this.versionId = versionId;
       this.scrProfileMenuDetailses = scrProfileMenuDetailses;
       this.scrUserMasters = scrUserMasters;
       this.scrMenuButtonProfileDetailses = scrMenuButtonProfileDetailses;
    }
   
    public String getProfileId() {
        return this.profileId;
    }
    
    public void setProfileId(String profileId) {
        this.profileId = profileId;
    }
    public String getProfileCode() {
        return this.profileCode;
    }
    
    public void setProfileCode(String profileCode) {
        this.profileCode = profileCode;
    }
    public String getProfileName() {
        return this.profileName;
    }
    
    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String profileStatus) {
        this.status = profileStatus;
    }
    public ScrUserMaster getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(ScrUserMaster createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public ScrUserMaster getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(ScrUserMaster updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public int getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(int versionId) {
        this.versionId = versionId;
    }
    public Set getScrProfileMenuDetailses() {
        return this.scrProfileMenuDetailses;
    }
    
    public void setScrProfileMenuDetailses(Set scrProfileMenuDetailses) {
        this.scrProfileMenuDetailses = scrProfileMenuDetailses;
    }
    public Set getScrUserMasters() {
        return this.scrUserMasters;
    }
    
    public void setScrUserMasters(Set scrUserMasters) {
        this.scrUserMasters = scrUserMasters;
    }
    public Set getScrMenuButtonProfileDetailses() {
        return this.scrMenuButtonProfileDetailses;
    }
    
    public void setScrMenuButtonProfileDetailses(Set scrMenuButtonProfileDetailses) {
        this.scrMenuButtonProfileDetailses = scrMenuButtonProfileDetailses;
    }




}


