package com.manikssys.in.security.beans;
// Generated Jun 23, 2010 5:14:05 PM by Hibernate Tools 3.2.1.GA



/**
 * ScrProfileMenuDetails generated by hbm2java
 */
public class ScrProfileMenuDetails  implements java.io.Serializable {


     private String profileMenuDtlsId;
     private ScrMenuMaster scrMenuMaster;
     private ScrUserProfileMaster scrUserProfileMaster;
     private String status;

    public ScrProfileMenuDetails() {
    }

	
    public ScrProfileMenuDetails(String profileMenuDtlsId) {
        this.profileMenuDtlsId = profileMenuDtlsId;
    }
    public ScrProfileMenuDetails(String profileMenuDtlsId, ScrMenuMaster scrMenuMaster, ScrUserProfileMaster scrUserProfileMaster, String profileMenuStatus) {
       this.profileMenuDtlsId = profileMenuDtlsId;
       this.scrMenuMaster = scrMenuMaster;
       this.scrUserProfileMaster = scrUserProfileMaster;
       this.status = profileMenuStatus;
    }
   
    public String getProfileMenuDtlsId() {
        return this.profileMenuDtlsId;
    }
    
    public void setProfileMenuDtlsId(String profileMenuDtlsId) {
        this.profileMenuDtlsId = profileMenuDtlsId;
    }
    public ScrMenuMaster getScrMenuMaster() {
        return this.scrMenuMaster;
    }
    
    public void setScrMenuMaster(ScrMenuMaster scrMenuMaster) {
        this.scrMenuMaster = scrMenuMaster;
    }
    public ScrUserProfileMaster getScrUserProfileMaster() {
        return this.scrUserProfileMaster;
    }
    
    public void setScrUserProfileMaster(ScrUserProfileMaster scrUserProfileMaster) {
        this.scrUserProfileMaster = scrUserProfileMaster;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String profileMenuStatus) {
        this.status = profileMenuStatus;
    }




}


