package com.manikssys.in.security.beans;
// Generated Jun 23, 2010 5:14:05 PM by Hibernate Tools 3.2.1.GA


import com.manikssys.in.operational.beans.OprBranchMaster;

import java.util.Date;

/**
 * ScrUserMaster generated by hbm2java
 */
public class ScrUserMaster  implements java.io.Serializable {


     private String userId;
     private OprBranchMaster oprBranchMaster;
     private ScrUserProfileMaster scrUserProfileMaster;
     private String userName;
     private String userPassword;
     private String userFullName;
     private String userTypeId;
     private String status;
     private String userEmail;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private String userTelephone;
     private String userMobile;
     private int versionId;

    public ScrUserMaster() {
    }

	
    public ScrUserMaster(String userId, String userName, int versionId) {
        this.userId = userId;
        this.userName = userName;
        this.versionId = versionId;
    }
    public ScrUserMaster(String userId, OprBranchMaster oprBranchMaster, ScrUserProfileMaster scrUserProfileMaster, String userName, String userPassword, String userTypeId, String userStatus, String userEmail, String createdBy, Date createdDate, String updatedBy, Date updatedDate, String userTelephone, String userMobile, int versionId) {
       this.userId = userId;
       this.oprBranchMaster = oprBranchMaster;
       this.scrUserProfileMaster = scrUserProfileMaster;
       this.userName = userName;
       this.userPassword = userPassword;
       this.userTypeId = userTypeId;
       this.status = userStatus;
       this.userEmail = userEmail;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.userTelephone = userTelephone;
       this.userMobile = userMobile;
       this.versionId = versionId;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public OprBranchMaster getOprBranchMaster() {
        return this.oprBranchMaster;
    }
    
    public void setOprBranchMaster(OprBranchMaster oprBranchMaster) {
        this.oprBranchMaster = oprBranchMaster;
    }
    public ScrUserProfileMaster getScrUserProfileMaster() {
        return this.scrUserProfileMaster;
    }
    
    public void setScrUserProfileMaster(ScrUserProfileMaster scrUserProfileMaster) {
        this.scrUserProfileMaster = scrUserProfileMaster;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public String getUserTypeId() {
        return this.userTypeId;
    }
    
    public void setUserTypeId(String userTypeId) {
        this.userTypeId = userTypeId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String userStatus) {
        this.status = userStatus;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public String getUserTelephone() {
        return this.userTelephone;
    }
    
    public void setUserTelephone(String userTelephone) {
        this.userTelephone = userTelephone;
    }
    public String getUserMobile() {
        return this.userMobile;
    }
    
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }
    public int getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(int versionId) {
        this.versionId = versionId;
    }

    public String getUserFullName() {
        return userFullName;
    }

    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }

     @Override
    public boolean equals(Object obj) {

        if (obj == null) {
            return false;
        }

        ScrUserMaster other = (ScrUserMaster) obj;

        if ((this.getUserId() == null) ? (other.getUserId() != null) : !this.getUserId().equalsIgnoreCase(other.getUserId())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + (this.userId != null ? this.userId.hashCode() : 0);
        return hash;
    }
}


