package com.manikssys.in.operational.beans;
// Generated Jul 1, 2010 2:48:31 PM by Hibernate Tools 3.2.1.GA


import com.manikssys.in.security.beans.ScrUserMaster;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OprPortMaster generated by hbm2java
 */
public class OprPortMaster  implements java.io.Serializable {

     private String portId;
     private String portCode;
     private String portName;
     private String status;
     private ScrUserMaster createdBy;
     private Date createdDate;
     private ScrUserMaster updatedBy;
     private Date updatedDate;
     private int versionId;
     private OprBranchMaster branchId;
     private Set oprEntryMasters = new HashSet(0);
     private Set oprVesselMastersForUnloadPortId = new HashSet(0);
     private Set oprVesselMastersForLoadPortId = new HashSet(0);
     private Set oprVesselMastersForNpoc = new HashSet(0);

     private int lwSeq;
     private int leSeq;
     private int dwSeq;
     private int deSeq;


    public OprPortMaster() {
    }

	
    public OprPortMaster(String portId, String portCode, String portName, int versionId) {
        this.portId = portId;
        this.portCode = portCode;
        this.portName = portName;
        this.versionId = versionId;
    }
    public OprPortMaster(String portId, String portCode, String portName, String portStatus, ScrUserMaster createdBy, Date createdDate, ScrUserMaster updatedBy, Date updatedDate, int versionId, Set oprEntryMasters, Set oprVesselMastersForUnloadPortId, Set oprVesselMastersForLoadPortId, Set oprVesselMastersForNpoc) {
       this.portId = portId;
       this.portCode = portCode;
       this.portName = portName;
       this.status = portStatus;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.versionId = versionId;
       this.oprEntryMasters = oprEntryMasters;
       this.oprVesselMastersForUnloadPortId = oprVesselMastersForUnloadPortId;
       this.oprVesselMastersForLoadPortId = oprVesselMastersForLoadPortId;
       this.oprVesselMastersForNpoc = oprVesselMastersForNpoc;
    }
   
    public String getPortId() {
        return this.portId;
    }
    
    public void setPortId(String portId) {
        this.portId = portId;
    }
    public String getPortCode() {
        return this.portCode;
    }
    
    public void setPortCode(String portCode) {
        this.portCode = portCode;
    }
    public String getPortName() {
        return this.portName;
    }
    
    public void setPortName(String portName) {
        this.portName = portName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String portStatus) {
        this.status = portStatus;
    }
    public ScrUserMaster getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(ScrUserMaster createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public ScrUserMaster getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(ScrUserMaster updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public int getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(int versionId) {
        this.versionId = versionId;
    }
    public Set getOprEntryMasters() {
        return this.oprEntryMasters;
    }
    
    public void setOprEntryMasters(Set oprEntryMasters) {
        this.oprEntryMasters = oprEntryMasters;
    }
    public Set getOprVesselMastersForUnloadPortId() {
        return this.oprVesselMastersForUnloadPortId;
    }
    
    public void setOprVesselMastersForUnloadPortId(Set oprVesselMastersForUnloadPortId) {
        this.oprVesselMastersForUnloadPortId = oprVesselMastersForUnloadPortId;
    }
    public Set getOprVesselMastersForLoadPortId() {
        return this.oprVesselMastersForLoadPortId;
    }
    
    public void setOprVesselMastersForLoadPortId(Set oprVesselMastersForLoadPortId) {
        this.oprVesselMastersForLoadPortId = oprVesselMastersForLoadPortId;
    }
    public Set getOprVesselMastersForNpoc() {
        return this.oprVesselMastersForNpoc;
    }
    
    public void setOprVesselMastersForNpoc(Set oprVesselMastersForNpoc) {
        this.oprVesselMastersForNpoc = oprVesselMastersForNpoc;
    }

    public OprBranchMaster getBranchId() {
        return branchId;
    }

    public void setBranchId(OprBranchMaster branchId) {
        this.branchId = branchId;
    }

    public int getDeSeq() {
        return deSeq;
    }

    public void setDeSeq(int deSeq) {
        this.deSeq = deSeq;
    }

    public int getDwSeq() {
        return dwSeq;
    }

    public void setDwSeq(int dwSeq) {
        this.dwSeq = dwSeq;
    }

    public int getLeSeq() {
        return leSeq;
    }

    public void setLeSeq(int leSeq) {
        this.leSeq = leSeq;
    }

    public int getLwSeq() {
        return lwSeq;
    }

    public void setLwSeq(int lwSeq) {
        this.lwSeq = lwSeq;
    }

    

    @Override
    public String toString() {
        return  portCode;
    }
}


