package com.manikssys.in.operational.beans;
// Generated Jul 1, 2010 2:48:31 PM by Hibernate Tools 3.2.1.GA


import com.manikssys.in.security.beans.ScrUserMaster;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OprBranchMaster generated by hbm2java
 */
public class OprBranchMaster  implements java.io.Serializable {


     private String branchId;
     private String branchCode;
     private String branchName;
     private String status;
     private String branchRoot;
     private String userAddr1;
     private String userAddr2;
     private String userAddr3;
     private String branchTelephone;
     private String branchTelex;
     private String branchFax;
     private String branchEmail;
     private ScrUserMaster createdBy;
     private Date createdDate;
     private ScrUserMaster updatedBy;
     private Date updatedDate;
     private int versionId;
     private Set scrUserMasters = new HashSet(0);

    public OprBranchMaster() {
    }

	
    public OprBranchMaster(String branchId, String branchCode, String branchName, int versionId) {
        this.branchId = branchId;
        this.branchCode = branchCode;
        this.branchName = branchName;
        this.versionId = versionId;
    }
    public OprBranchMaster(String branchId, String branchCode, String branchName, String branchStatus, String branchRoot, String userAddr1, String userAddr2, String userAddr3, String branchTelephone, String branchTelex, String branchFax, String branchEmail, ScrUserMaster createdBy, Date createdDate, ScrUserMaster updatedBy, Date updatedDate, int versionId, Set scrUserMasters) {
       this.branchId = branchId;
       this.branchCode = branchCode;
       this.branchName = branchName;
       this.status = branchStatus;
       this.branchRoot = branchRoot;
       this.userAddr1 = userAddr1;
       this.userAddr2 = userAddr2;
       this.userAddr3 = userAddr3;
       this.branchTelephone = branchTelephone;
       this.branchTelex = branchTelex;
       this.branchFax = branchFax;
       this.branchEmail = branchEmail;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.versionId = versionId;
       this.scrUserMasters = scrUserMasters;
    }
   
    public String getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String branchStatus) {
        this.status = branchStatus;
    }
    public String getBranchRoot() {
        return this.branchRoot;
    }
    
    public void setBranchRoot(String branchRoot) {
        this.branchRoot = branchRoot;
    }
    public String getUserAddr1() {
        return this.userAddr1;
    }
    
    public void setUserAddr1(String userAddr1) {
        this.userAddr1 = userAddr1;
    }
    public String getUserAddr2() {
        return this.userAddr2;
    }
    
    public void setUserAddr2(String userAddr2) {
        this.userAddr2 = userAddr2;
    }
    public String getUserAddr3() {
        return this.userAddr3;
    }
    
    public void setUserAddr3(String userAddr3) {
        this.userAddr3 = userAddr3;
    }
    public String getBranchTelephone() {
        return this.branchTelephone;
    }
    
    public void setBranchTelephone(String branchTelephone) {
        this.branchTelephone = branchTelephone;
    }
    public String getBranchTelex() {
        return this.branchTelex;
    }
    
    public void setBranchTelex(String branchTelex) {
        this.branchTelex = branchTelex;
    }
    public String getBranchFax() {
        return this.branchFax;
    }
    
    public void setBranchFax(String branchFax) {
        this.branchFax = branchFax;
    }
    public String getBranchEmail() {
        return this.branchEmail;
    }
    
    public void setBranchEmail(String branchEmail) {
        this.branchEmail = branchEmail;
    }
    public ScrUserMaster getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(ScrUserMaster createdBy) {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public ScrUserMaster getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(ScrUserMaster updatedBy) {
        this.updatedBy = updatedBy;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public int getVersionId() {
        return this.versionId;
    }
    
    public void setVersionId(int versionId) {
        this.versionId = versionId;
    }
    public Set getScrUserMasters() {
        return this.scrUserMasters;
    }
    
    public void setScrUserMasters(Set scrUserMasters) {
        this.scrUserMasters = scrUserMasters;
    }




}


